apiVersion: v1
kind: Secret
metadata:
  name: my-docker-secret
  namespace: my-namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIllXSm9ZWGx5WkdoNVlXNXBPbVJqYTNKZmNHRjBYMFJZZFMxbllUTXpjSHBUTVZGNmIxRmlWSGhJTkUxMVozUkRXUT09IgoJCX0KCX0KfQ==