apiVersion: v1
kind: Service
metadata:
  name: my-node-service
spec:
  selector:
    app: my-node-app
  ports:
  - protocol: TCP
    port: 8080         //This is the port that the Kubernetes Service will expose within the cluster. Other Pods in the same cluster will use this port to talk to your backend via the Service name (e.g., http://my-Node-service:<port>/api/hello).
    targetPort: 80    // This must be 80. This is the port your Node.js application is actually listening on inside its Pod.
  type: ClusterIP  // This is the default type. It means the Service is only accessible within the cluster. If you want to expose it outside the cluster, you can change this to NodePort