apiVersion: v1
kind: Service
metadata:
  name: my-Nginx-service
spec:
  selector:
    app: my-nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort # This is the port that the Kubernetes Service will expose within the cluster. Other Pods in the same cluster will use this port to talk to your backend via the Service name (e.g., http://my-Nginx-service:<port>/).