name: CI/CD for backend pod

on:
  push:
    branches:
      - main # This workflow will run whenever there's a push to the 'backend' branc

jobs:
  deploy: 
    runs-on: self-hosted

    steps:
      - name: getting into directory
        run: |
          pwd
          ./backend.sh
